INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resistance, retreat, card_number_in_collection, collection_id, type_id, stage_id) VALUES
(60, 'Bulbasaur', 'Seed Pokémon.', 'Vine Whip', '20', 'Fire', '', '1 Energy', 44, 1, 1, 1),
(80, 'Ivysaur', 'Seed Pokémon.', 'Razor Leaf', '30', 'Fire', '', '2 Energy', 30, 1, 1, 2),
(100, 'Venusaur', 'Seed Pokémon.', 'Solarbeam', '60', 'Fire', '', '3 Energy', 15, 1, 1, 3),
(50, 'Charmander', 'Lizard Pokémon.', 'Ember', '30', 'Water', '', '1 Energy', 46, 1, 2, 1),
(80, 'Charmeleon', 'Flame Pokémon.', 'Flamethrower', '50', 'Water', '', '2 Energy', 24, 1, 2, 2),
(120, 'Charizard', 'Flame Pokémon.', 'Fire Spin', '100', 'Water', '', '3 Energy', 4, 1, 2, 3),
(40, 'Squirtle', 'Tiny Turtle Pokémon.', 'Bubble', '10', 'Electric', '', '1 Energy', 63, 1, 3, 1),
(70, 'Wartortle', 'Turtle Pokémon.', 'Water Gun', '30', 'Electric', '', '2 Energy', 42, 1, 3, 2),
(100, 'Blastoise', 'Shellfish Pokémon.', 'Hydro Pump', '60+', 'Electric', '', '3 Energy', 2, 1, 3, 3),
(60, 'Pikachu', 'Mouse Pokémon.', 'Thunder Shock', '30', 'Fighting', '', '1 Energy', 58, 1, 4, 1),
(90, 'Raichu', 'Mouse Pokémon.', 'Thunderbolt', '60', 'Fighting', '', '2 Energy', 14, 1, 4, 2),
(50, 'Abra', 'Psi Pokémon.', 'Psyshock', '20', 'Darkness', '', '1 Energy', 55, 1, 5, 1),
(70, 'Kadabra', 'Psi Pokémon.', 'Confuse Ray', '30', 'Darkness', '', '2 Energy', 32, 1, 5, 2),
(100, 'Alakazam', 'Psi Pokémon.', 'Psychic', '60', 'Darkness', '', '3 Energy', 1, 1, 5, 3),
(60, 'Machop', 'Superpower Pokémon.', 'Karate Chop', '20', 'Psychic', '', '1 Energy', 52, 1, 6, 1),
(80, 'Machoke', 'Superpower Pokémon.', 'Submission', '50', 'Psychic', '', '2 Energy', 31, 1, 6, 2),
(110, 'Machamp', 'Superpower Pokémon.', 'Seismic Toss', '60', 'Psychic', '', '3 Energy', 8, 1, 6, 3),
(70, 'Meowth', 'Scratch Cat Pokémon.', 'Pay Day', '20', 'Fighting', '', '1 Energy', 56, 2, 11, 1),
(90, 'Persian', 'Classy Cat Pokémon.', 'Slash', '40', 'Fighting', '', '2 Energy', 33, 2, 11, 2),
(60, 'Oddish', 'Weed Pokémon.', 'Stun Spore', '20', 'Fire', '', '1 Energy', 49, 2, 1, 1);