INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resistance, retreat, card_number_in_collection, collection_id, type_id, stage_id) VALUES
(50, 'Sandshrew', 'Mouse Pokémon.', 'Scratch', '20', 'Water', '', '1 Energy', 37, 1, 6, 1),
(80, 'Sandslash', 'Mouse Pokémon.', 'Slash', '40', 'Water', '', '2 Energy', 16, 1, 6, 2),
(60, 'Psyduck', 'Duck Pokémon.', 'Headache', '10', 'Electric', '', '1 Energy', 36, 1, 3, 1),
(80, 'Golduck', 'Duck Pokémon.', 'Confusion Wave', '40', 'Electric', '', '2 Energy', 13, 1, 3, 2),
(50, 'Tentacool', 'Jellyfish Pokémon.', 'Acid', '20', 'Psychic', '', '1 Energy', 35, 3, 3, 1),
(80, 'Tentacruel', 'Jellyfish Pokémon.', 'Poison Sting', '40', 'Psychic', '', '2 Energy', 26, 3, 3, 2),
(60, 'Grimer', 'Sludge Pokémon.', 'Sludge Toss', '20', 'Psychic', '', '1 Energy', 34, 3, 7, 1),
(90, 'Muk', 'Sludge Pokémon.', 'Toxic', '50', 'Psychic', '', '2 Energy', 25, 3, 7, 2),
(50, 'Voltorb', 'Ball Pokémon.', 'Charge', '10', 'Fighting', '', '1 Energy', 33, 1, 4, 1),
(80, 'Electrode', 'Ball Pokémon.', 'Explosion', '60', 'Fighting', '', '2 Energy', 14, 1, 4, 2),
(60, 'Koffing', 'Poison Gas Pokémon.', 'Smog', '20', 'Psychic', '', '1 Energy', 32, 3, 7, 1),
(90, 'Weezing', 'Poison Gas Pokémon.', 'Gas Bomb', '50', 'Psychic', '', '2 Energy', 13, 3, 7, 2),
(70, 'Rhyhorn', 'Spikes Pokémon.', 'Horn Attack', '30', 'Grass', '', '1 Energy', 31, 3, 6, 1),
(100, 'Rhydon', 'Drill Pokémon.', 'Earthquake', '60', 'Grass', '', '2 Energy', 12, 3, 6, 2),
(60, 'Horsea', 'Dragon Pokémon.', 'Bubble', '10', 'Electric', '', '1 Energy', 30, 3, 3, 1),
(80, 'Seadra', 'Dragon Pokémon.', 'Water Gun', '40', 'Electric', '', '2 Energy', 11, 3, 3, 2),
(100, 'Kingdra', 'Dragon Pokémon.', 'Dragon Blast', '60', 'Fairy', '', '3 Energy', 4, 3, 10, 3),
(50, 'Staryu', 'Star Shape Pokémon.', 'Swift', '20', 'Electric', '', '1 Energy', 29, 3, 3, 1),
(80, 'Starmie', 'Mysterious Pokémon.', 'Rapid Spin', '40', 'Electric', '', '2 Energy', 10, 3, 3, 2),
(60, 'Scyther', 'Mantis Pokémon.', 'Slash', '30', 'Fire', '', '1 Energy', 28, 2, 1, 1),
(90, 'Pinsir', 'Stag Beetle Pokémon.', 'Guillotine', '50', 'Fire', '', '2 Energy', 9, 2, 1, 1),
(70, 'Tauros', 'Wild Bull Pokémon.', 'Rampage', '40', 'Fighting', '', '2 Energy', 27, 2, 11, 1),
(60, 'Doduo', 'Twin Bird Pokémon.', 'Peck', '20', 'Lightning', '', '1 Energy', 26, 2, 11, 1),
(80, 'Dodrio', 'Triple Bird Pokémon.', 'Tri Attack', '50', 'Lightning', '', '2 Energy', 8, 2, 11, 2),
(50, 'Seel', 'Sea Lion Pokémon.', 'Headbutt', '20', 'Electric', '', '1 Energy', 25, 1, 3, 1),
(90, 'Dewgong', 'Sea Lion Pokémon.', 'Aurora Beam', '50', 'Electric', '', '2 Energy', 7, 1, 3, 2),
(60, 'Shellder', 'Bivalve Pokémon.', 'Clamp', '20', 'Electric', '', '1 Energy', 24, 1, 3, 1),
(80, 'Cloyster', 'Bivalve Pokémon.', 'Spike Cannon', '40', 'Electric', '', '2 Energy', 6, 1, 3, 2),
(70, 'Krabby', 'River Crab Pokémon.', 'Crabhammer', '30', 'Electric', '', '1 Energy', 23, 3, 3, 1),
(100, 'Kingler', 'Pincer Pokémon.', 'Crabhammer', '60', 'Electric', '', '2 Energy', 5, 3, 3, 2);